version: '3'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [
      "redis-server",    
      "--requirepass", "d41d8cd98f00b204e9800998ecf8427e",
      "--aclfile", "/certs/users.acl"
    ]
    volumes:
      - ./redis-data:/data
      - ./certs:/certs
